import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { Roboto_Flex } from "next/font/google";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.variable} antialiased w-screen overflow-x-hidden max-w-3xl px-2 md:mx-auto font-sans`}
      >
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
